module.exports= {
    products: [
        {
            _id: '1',
            name: 'PSG Home Kit',
            category: 'Shirts',
            image:'/images/product-1.jpg',
            price: 2599,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 15,
            countInStock: 15,          
        },
        {
            _id: '2',
            name: 'Arsenal Home Kit',
            category: 'Shirts',
            image:'/images/product-2.jpg',
            price: 2999,
            brand: 'Puma',
            rating: 4.9,
            numReviews: 96,
            countInStock: 20,          
        },
        {
            _id: '3',
            name: 'FC Barcelona Home Kit',
            category: 'Shirts',
            image:'/images/product-3.jpg',
            price: 2499,
            brand: 'Nike',
            rating: 4.2,
            numReviews: 8,
            countInStock: 33,          
        },
        {
            _id: '4',
            name: 'Manchester United Home Kit',
            category: 'Shirts',
            image:'/images/product-4.jpg',
            price: 2699,
            brand: 'Adidas',
            rating: 4.7,
            numReviews: 50,
            countInStock: 16,          
        },
        {
            _id: '5',
            name: 'Juventus Home Kit',
            category: 'Shirts',
            image:'/images/product-5.jpg',
            price: 2299,
            brand: 'Adidas',
            rating: 4.0,
            numReviews: 12,
            countInStock: 16,          
        },
        {
            _id: '6',
            name: 'Liberpool FC Home Kit',
            category: 'Shirts',
            image:'/images/product-6.jpg',
            price: 2499,
            brand: 'Nike',
            rating: 4.6,
            numReviews: 40,
            countInStock: 36,          
        },
        {
            _id: '7',
            name: 'Manchester City Home Kit',
            category: 'Shirts',
            image:'/images/product-7.jpg',
            price: 2999,
            brand: 'Nike',
            rating: 4.8,
            numReviews: 56,
            countInStock: 26,          
        },
        {
            _id: '8',
            name: 'AC Milan Home Kit',
            category: 'Shirts',
            image:'/images/product-8.jpg',
            price: 2399,
            brand: 'Puma',
            rating: 4.0,
            numReviews: 10,
            countInStock: 16,          
        },
        {
            _id: '9',
            name: 'Chelsea Home Kit',
            category: 'Shirts',
            image:'/images/product-9.jpg',
            price: 2899,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 25,
            countInStock: 6,          
        },
        {
            _id: '10',
            name: 'Bayern Munich Home Kit',
            category: 'Shirts',
            image:'/images/product-10.jpg',
            price: 3299,
            brand: 'Adidas',
            rating: 4.9,
            numReviews: 96,
            countInStock: 56,          
        },
        {
            _id: '11',
            name: 'Dortmund Home Kit',
            category: 'Shirts',
            image:'/images/product-11.jpg',
            price: 2199,
            brand: 'Puma',
            rating: 3.9,
            numReviews: 14,
            countInStock: 16,          
        },
        {
            _id: '12',
            name: 'Real Madird Home Kit',
            category: 'Shirts',
            image:'/images/product-12.jpg',
            price: 3999,
            brand: 'Adidas',
            rating: 5.0,
            numReviews: 96,
            countInStock: 56,          
        },
        {
            _id: '13',
            name: 'Atletico Madrid Home Kit',
            category: 'Shirts',
            image:'/images/product-13.jpg',
            price: 2499,
            brand: 'Nike',
            rating: 4.2,
            numReviews: 16,
            countInStock: 6,          
        },
        {
            _id: '14',
            name: 'Tottenham Hotspurs Home Kit',
            category: 'Shirts',
            image:'/images/product-14.jpg',
            price: 2999,
            brand: 'Nike',
            rating: 4.8,
            numReviews: 26,
            countInStock: 36,          
        },
        {
            _id: '15',
            name: 'Napoli Home Kit',
            category: 'Shirts',
            image:'/images/product-15.jpg',
            price: 2599,
            brand: 'Kappa',
            rating: 4.0,
            numReviews: 15,
            countInStock: 15,          
        },
        {
            _id: '16',
            name: 'Galatasary Home Kit',
            category: 'Shirts',
            image:'/images/product-16.jpg',
            price: 2599,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 13,
            countInStock: 17,          
        },
        
    ],
};